2021-05-27 12:47:20 INFO run.py:219 GNS3 server version 2.2.21
2021-05-27 12:47:20 INFO run.py:221 Copyright (c) 2007-2021 GNS3 Technologies Inc.
2021-05-27 12:47:20 INFO run.py:224 Config file /home/saad/.config/GNS3/2.2/gns3_server.conf loaded
2021-05-27 12:47:20 WARNING run.py:230 Local mode is enabled. Beware, clients will have full control on your filesystem
2021-05-27 12:47:20 INFO run.py:243 Running with Python 3.9.5 and has PID 31967
2021-05-27 12:47:20 INFO run.py:79 Current locale is en_US.UTF-8
2021-05-27 12:47:20 WARNING port_manager.py:92 Remote console connections are allowed
2021-05-27 12:47:20 INFO web_server.py:318 Starting server on localhost:3080
2021-05-27 12:47:20 INFO __init__.py:63 Load controller configuration file /home/saad/.config/GNS3/2.2/gns3_controller.conf
2021-05-27 12:47:20 INFO __init__.py:67 Controller is starting
2021-05-27 12:47:20 INFO compute.py:64 Create compute local
2021-05-27 12:47:20 INFO compute.py:364 Connecting to compute 'local'
2021-05-27 12:47:20 INFO web_log.py:206 ::1 [27/May/2021:07:47:20 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 552 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:20 INFO web_log.py:206 ::1 [27/May/2021:07:47:20 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.2.21"
2021-05-27 12:47:20 INFO notification_handler.py:50 New client has connected to compute WebSocket
2021-05-27 12:47:20 INFO compute.py:434 Connected to compute 'local' WebSocket 'http://localhost:3080/v2/compute/notifications/ws'
2021-05-27 12:47:20 INFO web_log.py:206 ::1 [27/May/2021:07:47:20 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.2.21"
2021-05-27 12:47:20 INFO notification_handler.py:73 New client has connected to controller WebSocket
2021-05-27 12:47:20 INFO web_log.py:206 ::1 [27/May/2021:07:47:20 +0000] "GET /v2/templates HTTP/1.1" 200 20723 "-" "GNS3 QT Client v2.2.21"
2021-05-27 12:47:20 INFO web_log.py:206 ::1 [27/May/2021:07:47:20 +0000] "GET /v2/appliances?symbol_theme=Affinity-circle-blue HTTP/1.1" 200 795244 "-" "GNS3 QT Client v2.2.21"
2021-05-27 12:47:20 INFO web_log.py:206 ::1 [27/May/2021:07:47:20 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 12:47:20 INFO web_log.py:206 ::1 [27/May/2021:07:47:20 +0000] "GET /v2/projects HTTP/1.1" 200 29956 "-" "GNS3 QT Client v2.2.21"
2021-05-27 12:47:20 INFO web_log.py:206 ::1 [27/May/2021:07:47:20 +0000] "GET /v2/projects HTTP/1.1" 200 29956 "-" "GNS3 QT Client v2.2.21"
2021-05-27 12:47:25 INFO project.py:78 Project 2a56fee1-bb43-4cda-a5f5-1ab3c90677e4 with path '/home/saad/GNS3/projects/lab_for_programming' created
2021-05-27 12:47:25 INFO web_log.py:206 ::1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects HTTP/1.1" 201 314 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO nat.py:51 NAT node 'NAT1' configured to use NAT interface 'virbr0'
2021-05-27 12:47:25 INFO base_node.py:655 Starting new uBridge hypervisor localhost:41845
2021-05-27 12:47:25 INFO hypervisor.py:169 starting ubridge: ['/sbin/ubridge', '-H', 'localhost:41845']
2021-05-27 12:47:25 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/lab_for_programming/project-files/builtin/9c32e5f4-9a89-4939-82c0-22ddd64553a7/ubridge.log
2021-05-27 12:47:25 INFO hypervisor.py:179 ubridge started PID=32042
2021-05-27 12:47:25 INFO base_node.py:658 Hypervisor localhost:41845 has successfully started
2021-05-27 12:47:25 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:41845 after 0.1028 seconds
2021-05-27 12:47:25 INFO cloud.py:215 Cloud "NAT1" [9c32e5f4-9a89-4939-82c0-22ddd64553a7] has been created
2021-05-27 12:47:25 INFO web_log.py:206 127.0.0.1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/nat/nodes HTTP/1.1" 201 553 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO iou_vm.py:73 IOU "R1" [f9b76d55-6850-4935-8f45-21e906e87c04]: assigned with application ID 1
2021-05-27 12:47:25 INFO iou_vm.py:848 IOU "R1" [f9b76d55-6850-4935-8f45-21e906e87c04]: number of Ethernet adapters changed to 2
2021-05-27 12:47:25 INFO iou_vm.py:876 IOU "R1" [f9b76d55-6850-4935-8f45-21e906e87c04]: number of Serial adapters changed to 2
2021-05-27 12:47:25 INFO iou_vm.py:316 IOU "R1" [f9b76d55-6850-4935-8f45-21e906e87c04]: NVRAM updated from 128KB to 64KB
2021-05-27 12:47:25 INFO iou_vm.py:848 IOU "R1" [f9b76d55-6850-4935-8f45-21e906e87c04]: number of Ethernet adapters changed to 3
2021-05-27 12:47:25 INFO iou_vm.py:145 IOU "R1" [f9b76d55-6850-4935-8f45-21e906e87c04]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin"
2021-05-27 12:47:25 INFO iou_vm.py:876 IOU "R1" [f9b76d55-6850-4935-8f45-21e906e87c04]: number of Serial adapters changed to 1
2021-05-27 12:47:25 INFO web_log.py:206 ::1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes HTTP/1.1" 201 881 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO iou_vm.py:73 IOU "R2" [49fc733e-16b0-4831-a5bb-47e90526e662]: assigned with application ID 2
2021-05-27 12:47:25 INFO iou_vm.py:848 IOU "R2" [49fc733e-16b0-4831-a5bb-47e90526e662]: number of Ethernet adapters changed to 2
2021-05-27 12:47:25 INFO iou_vm.py:876 IOU "R2" [49fc733e-16b0-4831-a5bb-47e90526e662]: number of Serial adapters changed to 2
2021-05-27 12:47:25 INFO iou_vm.py:316 IOU "R2" [49fc733e-16b0-4831-a5bb-47e90526e662]: NVRAM updated from 128KB to 64KB
2021-05-27 12:47:25 INFO iou_vm.py:848 IOU "R2" [49fc733e-16b0-4831-a5bb-47e90526e662]: number of Ethernet adapters changed to 3
2021-05-27 12:47:25 INFO iou_vm.py:145 IOU "R2" [49fc733e-16b0-4831-a5bb-47e90526e662]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin"
2021-05-27 12:47:25 INFO iou_vm.py:876 IOU "R2" [49fc733e-16b0-4831-a5bb-47e90526e662]: number of Serial adapters changed to 1
2021-05-27 12:47:25 INFO web_log.py:206 127.0.0.1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes HTTP/1.1" 201 881 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO iou_vm.py:73 IOU "S1" [95ad63d1-5f53-4794-8366-2a7900692b25]: assigned with application ID 3
2021-05-27 12:47:25 INFO iou_vm.py:848 IOU "S1" [95ad63d1-5f53-4794-8366-2a7900692b25]: number of Ethernet adapters changed to 2
2021-05-27 12:47:25 INFO iou_vm.py:876 IOU "S1" [95ad63d1-5f53-4794-8366-2a7900692b25]: number of Serial adapters changed to 2
2021-05-27 12:47:25 INFO iou_vm.py:316 IOU "S1" [95ad63d1-5f53-4794-8366-2a7900692b25]: NVRAM updated from 128KB to 16KB
2021-05-27 12:47:25 INFO iou_vm.py:848 IOU "S1" [95ad63d1-5f53-4794-8366-2a7900692b25]: number of Ethernet adapters changed to 4
2021-05-27 12:47:25 INFO iou_vm.py:145 IOU "S1" [95ad63d1-5f53-4794-8366-2a7900692b25]: IOU image updated to "/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.1a.bin"
2021-05-27 12:47:25 INFO iou_vm.py:876 IOU "S1" [95ad63d1-5f53-4794-8366-2a7900692b25]: number of Serial adapters changed to 0
2021-05-27 12:47:25 INFO web_log.py:206 ::1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes HTTP/1.1" 201 876 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO docker_vm.py:1058 Docker container "debian-1" [46701752-b447-49c3-9e1f-6828f9b97d97]: number of Ethernet adapters changed to 1
2021-05-27 12:47:25 INFO docker_vm.py:406 Docker container 'debian-1' [46701752-b447-49c3-9e1f-6828f9b97d97] created
2021-05-27 12:47:25 INFO web_log.py:206 127.0.0.1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/docker/nodes HTTP/1.1" 201 935 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO web_log.py:206 ::1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO web_log.py:206 127.0.0.1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO iou_vm.py:902 IOU "S1" [95ad63d1-5f53-4794-8366-2a7900692b25]: NIO UDP added to 0/0
2021-05-27 12:47:25 INFO web_log.py:206 ::1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes/95ad63d1-5f53-4794-8366-2a7900692b25/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO docker_vm.py:960 Docker container 'debian-1' [46701752-b447-49c3-9e1f-6828f9b97d97]: NIO UDP added to adapter 0
2021-05-27 12:47:25 INFO web_log.py:206 127.0.0.1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/docker/nodes/46701752-b447-49c3-9e1f-6828f9b97d97/adapters/0/ports/0/nio HTTP/1.1" 201 380 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO web_log.py:206 ::1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO web_log.py:206 127.0.0.1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO iou_vm.py:902 IOU "S1" [95ad63d1-5f53-4794-8366-2a7900692b25]: NIO UDP added to 0/1
2021-05-27 12:47:25 INFO web_log.py:206 ::1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes/95ad63d1-5f53-4794-8366-2a7900692b25/adapters/0/ports/1/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO iou_vm.py:902 IOU "R2" [49fc733e-16b0-4831-a5bb-47e90526e662]: NIO UDP added to 0/0
2021-05-27 12:47:25 INFO web_log.py:206 127.0.0.1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes/49fc733e-16b0-4831-a5bb-47e90526e662/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO web_log.py:206 ::1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO web_log.py:206 127.0.0.1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO iou_vm.py:902 IOU "R2" [49fc733e-16b0-4831-a5bb-47e90526e662]: NIO UDP added to 3/0
2021-05-27 12:47:25 INFO web_log.py:206 ::1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes/49fc733e-16b0-4831-a5bb-47e90526e662/adapters/3/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO iou_vm.py:902 IOU "R1" [f9b76d55-6850-4935-8f45-21e906e87c04]: NIO UDP added to 3/0
2021-05-27 12:47:25 INFO web_log.py:206 127.0.0.1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes/f9b76d55-6850-4935-8f45-21e906e87c04/adapters/3/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO web_log.py:206 ::1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO web_log.py:206 127.0.0.1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/ports/udp HTTP/1.1" 201 243 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO iou_vm.py:902 IOU "R1" [f9b76d55-6850-4935-8f45-21e906e87c04]: NIO UDP added to 0/0
2021-05-27 12:47:25 INFO web_log.py:206 ::1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes/f9b76d55-6850-4935-8f45-21e906e87c04/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO cloud.py:396 Cloud "NAT1" [9c32e5f4-9a89-4939-82c0-22ddd64553a7]: NIO NIO UDP bound to port 0
2021-05-27 12:47:25 INFO web_log.py:206 127.0.0.1 [27/May/2021:07:47:25 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/nat/nodes/9c32e5f4-9a89-4939-82c0-22ddd64553a7/adapters/0/ports/0/nio HTTP/1.1" 201 377 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:25 INFO web_log.py:206 ::1 [27/May/2021:07:47:24 +0000] "POST /v2/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/open HTTP/1.1" 201 775 "-" "GNS3 QT Client v2.2.21"
2021-05-27 12:47:25 INFO project_handler.py:271 New client has connected to the notification stream for project ID '2a56fee1-bb43-4cda-a5f5-1ab3c90677e4' (WebSocket method)
2021-05-27 12:47:25 INFO web_log.py:206 ::1 [27/May/2021:07:47:25 +0000] "GET /v2/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/nodes HTTP/1.1" 200 24690 "-" "GNS3 QT Client v2.2.21"
2021-05-27 12:47:25 INFO web_log.py:206 ::1 [27/May/2021:07:47:25 +0000] "GET /v2/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/links HTTP/1.1" 200 5422 "-" "GNS3 QT Client v2.2.21"
2021-05-27 12:47:25 INFO web_log.py:206 ::1 [27/May/2021:07:47:25 +0000] "GET /v2/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/drawings HTTP/1.1" 200 205 "-" "GNS3 QT Client v2.2.21"
2021-05-27 12:47:26 INFO web_log.py:206 ::1 [27/May/2021:07:47:26 +0000] "GET /v2/computes HTTP/1.1" 200 1021 "-" "GNS3 QT Client v2.2.21"
2021-05-27 12:47:28 INFO web_log.py:206 127.0.0.1 [27/May/2021:07:47:28 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/nat/nodes/9c32e5f4-9a89-4939-82c0-22ddd64553a7/start HTTP/1.1" 204 225 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:28 INFO iou_vm.py:414 Checking IOU license in '/tmp/tmp9yqqyna3/iourc'
2021-05-27 12:47:28 INFO iou_vm.py:414 Checking IOU license in '/tmp/tmp_vtsbn3s/iourc'
2021-05-27 12:47:28 INFO base_node.py:655 Starting new uBridge hypervisor localhost:46709
2021-05-27 12:47:28 INFO base_node.py:655 Starting new uBridge hypervisor localhost:46355
2021-05-27 12:47:28 INFO hypervisor.py:169 starting ubridge: ['/sbin/ubridge', '-H', 'localhost:46709']
2021-05-27 12:47:28 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/lab_for_programming/project-files/iou/49fc733e-16b0-4831-a5bb-47e90526e662/ubridge.log
2021-05-27 12:47:28 INFO hypervisor.py:179 ubridge started PID=32109
2021-05-27 12:47:28 INFO base_node.py:658 Hypervisor localhost:46709 has successfully started
2021-05-27 12:47:28 INFO iou_vm.py:414 Checking IOU license in '/tmp/tmp716l1cap/iourc'
2021-05-27 12:47:28 INFO hypervisor.py:169 starting ubridge: ['/sbin/ubridge', '-H', 'localhost:46355']
2021-05-27 12:47:28 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/lab_for_programming/project-files/iou/f9b76d55-6850-4935-8f45-21e906e87c04/ubridge.log
2021-05-27 12:47:28 INFO hypervisor.py:179 ubridge started PID=32113
2021-05-27 12:47:28 INFO base_node.py:658 Hypervisor localhost:46355 has successfully started
2021-05-27 12:47:28 INFO base_node.py:655 Starting new uBridge hypervisor localhost:38971
2021-05-27 12:47:28 INFO hypervisor.py:169 starting ubridge: ['/sbin/ubridge', '-H', 'localhost:38971']
2021-05-27 12:47:28 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/lab_for_programming/project-files/iou/95ad63d1-5f53-4794-8366-2a7900692b25/ubridge.log
2021-05-27 12:47:28 INFO hypervisor.py:179 ubridge started PID=32117
2021-05-27 12:47:28 INFO base_node.py:658 Hypervisor localhost:38971 has successfully started
2021-05-27 12:47:28 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:46709 after 0.1029 seconds
2021-05-27 12:47:28 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:46355 after 0.1021 seconds
2021-05-27 12:47:28 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:38971 after 0.1027 seconds
2021-05-27 12:47:28 INFO iou_vm.py:753 IOU R2 [id=49fc733e-16b0-4831-a5bb-47e90526e662]: NETMAP file created
2021-05-27 12:47:28 INFO iou_vm.py:551 Starting IOU: ['/home/saad/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin', '-e', '3', '-s', '1', '2']
2021-05-27 12:47:28 INFO iou_vm.py:753 IOU R1 [id=f9b76d55-6850-4935-8f45-21e906e87c04]: NETMAP file created
2021-05-27 12:47:28 INFO iou_vm.py:560 IOU instance 49fc733e-16b0-4831-a5bb-47e90526e662 started PID=32127
2021-05-27 12:47:28 INFO iou_vm.py:753 IOU S1 [id=95ad63d1-5f53-4794-8366-2a7900692b25]: NETMAP file created
2021-05-27 12:47:28 INFO iou_vm.py:551 Starting IOU: ['/home/saad/GNS3/images/IOU/i86bi-linux-l3-adventerprisek9-ms.155-2.T.bin', '-e', '3', '-s', '1', '1']
2021-05-27 12:47:28 INFO iou_vm.py:551 Starting IOU: ['/home/saad/GNS3/images/IOU/i86bi-linux-l2-adventerprisek9-15.1a.bin', '-e', '4', '-s', '0', '3']
2021-05-27 12:47:28 INFO iou_vm.py:560 IOU instance f9b76d55-6850-4935-8f45-21e906e87c04 started PID=32133
2021-05-27 12:47:28 INFO iou_vm.py:560 IOU instance 95ad63d1-5f53-4794-8366-2a7900692b25 started PID=32135
2021-05-27 12:47:28 INFO web_log.py:206 ::1 [27/May/2021:07:47:28 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes/49fc733e-16b0-4831-a5bb-47e90526e662/start HTTP/1.1" 200 976 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:28 INFO web_log.py:206 ::1 [27/May/2021:07:47:28 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes/f9b76d55-6850-4935-8f45-21e906e87c04/start HTTP/1.1" 200 976 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:28 INFO web_log.py:206 127.0.0.1 [27/May/2021:07:47:28 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/iou/nodes/95ad63d1-5f53-4794-8366-2a7900692b25/start HTTP/1.1" 200 966 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:28 INFO base_node.py:655 Starting new uBridge hypervisor localhost:33625
2021-05-27 12:47:28 INFO hypervisor.py:169 starting ubridge: ['/sbin/ubridge', '-H', 'localhost:33625']
2021-05-27 12:47:28 INFO hypervisor.py:171 logging to /home/saad/GNS3/projects/lab_for_programming/project-files/docker/46701752-b447-49c3-9e1f-6828f9b97d97/ubridge.log
2021-05-27 12:47:28 INFO hypervisor.py:179 ubridge started PID=32217
2021-05-27 12:47:28 INFO base_node.py:658 Hypervisor localhost:33625 has successfully started
2021-05-27 12:47:29 INFO ubridge_hypervisor.py:83 Connected to uBridge hypervisor on localhost:33625 after 0.1036 seconds
2021-05-27 12:47:29 INFO docker_vm.py:499 Docker container 'debian-1' [debian:latest] started listen for telnet on 5004
2021-05-27 12:47:29 INFO web_log.py:206 ::1 [27/May/2021:07:47:28 +0000] "POST /v2/compute/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/docker/nodes/46701752-b447-49c3-9e1f-6828f9b97d97/start HTTP/1.1" 204 228 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 12:47:29 INFO web_log.py:206 ::1 [27/May/2021:07:47:28 +0000] "POST /v2/projects/2a56fee1-bb43-4cda-a5f5-1ab3c90677e4/nodes/start HTTP/1.1" 204 203 "-" "GNS3 QT Client v2.2.21"
2021-05-27 12:47:30 INFO web_log.py:206 ::1 [27/May/2021:07:47:30 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 12:53:32 INFO web_log.py:206 ::1 [27/May/2021:07:53:32 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 12:59:33 INFO web_log.py:206 ::1 [27/May/2021:07:59:33 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 13:04:23 INFO web_log.py:206 ::1 [27/May/2021:08:04:23 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 13:10:34 INFO web_log.py:206 ::1 [27/May/2021:08:10:34 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 13:15:52 INFO web_log.py:206 ::1 [27/May/2021:08:15:52 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 13:21:23 INFO web_log.py:206 ::1 [27/May/2021:08:21:23 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 13:21:25 INFO web_log.py:206 ::1 [27/May/2021:08:21:25 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 13:26:43 INFO web_log.py:206 ::1 [27/May/2021:08:26:43 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.21"
2021-05-27 13:32:12 INFO web_log.py:206 ::1 [27/May/2021:08:32:12 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 13:37:29 INFO web_log.py:206 ::1 [27/May/2021:08:37:29 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 13:43:21 INFO web_log.py:206 ::1 [27/May/2021:08:43:21 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.21"
2021-05-27 13:48:36 INFO web_log.py:206 ::1 [27/May/2021:08:48:36 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.21"
2021-05-27 13:54:16 INFO web_log.py:206 ::1 [27/May/2021:08:54:16 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.21"
2021-05-27 13:59:23 INFO web_log.py:206 ::1 [27/May/2021:08:59:23 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.21"
2021-05-27 14:05:13 INFO web_log.py:206 ::1 [27/May/2021:09:05:13 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.21"
2021-05-27 14:10:56 INFO web_log.py:206 ::1 [27/May/2021:09:10:56 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 14:16:06 INFO web_log.py:206 ::1 [27/May/2021:09:16:06 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.21"
2021-05-27 14:16:08 INFO web_log.py:206 ::1 [27/May/2021:09:16:08 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.21"
2021-05-27 14:21:39 INFO web_log.py:206 ::1 [27/May/2021:09:21:39 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 14:26:55 INFO web_log.py:206 ::1 [27/May/2021:09:26:55 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 14:32:58 INFO web_log.py:206 ::1 [27/May/2021:09:32:58 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.21"
2021-05-27 14:37:52 INFO web_log.py:206 ::1 [27/May/2021:09:37:52 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 14:43:54 INFO web_log.py:206 ::1 [27/May/2021:09:43:54 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 14:48:37 INFO web_log.py:206 ::1 [27/May/2021:09:48:37 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 14:54:34 INFO web_log.py:206 ::1 [27/May/2021:09:54:34 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 14:54:36 INFO web_log.py:206 ::1 [27/May/2021:09:54:36 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 14:59:28 INFO web_log.py:206 ::1 [27/May/2021:09:59:28 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 15:05:37 INFO web_log.py:206 ::1 [27/May/2021:10:05:37 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.2.21"
2021-05-27 15:10:33 INFO web_log.py:206 ::1 [27/May/2021:10:10:33 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 15:16:12 INFO web_log.py:206 ::1 [27/May/2021:10:16:12 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 15:21:19 INFO web_log.py:206 ::1 [27/May/2021:10:21:19 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 15:26:55 INFO web_log.py:206 ::1 [27/May/2021:10:26:55 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 15:31:48 INFO web_log.py:206 ::1 [27/May/2021:10:31:48 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 15:37:47 INFO web_log.py:206 ::1 [27/May/2021:10:37:47 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 15:42:45 INFO web_log.py:206 ::1 [27/May/2021:10:42:45 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 15:48:55 INFO web_log.py:206 ::1 [27/May/2021:10:48:55 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 15:54:19 INFO web_log.py:206 ::1 [27/May/2021:10:54:19 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 15:59:22 INFO web_log.py:206 ::1 [27/May/2021:10:59:22 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 15:59:24 INFO web_log.py:206 ::1 [27/May/2021:10:59:24 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 16:04:45 INFO web_log.py:206 ::1 [27/May/2021:11:04:45 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 16:10:05 INFO web_log.py:206 ::1 [27/May/2021:11:10:05 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 16:15:40 INFO web_log.py:206 ::1 [27/May/2021:11:15:40 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 16:20:42 INFO web_log.py:206 ::1 [27/May/2021:11:20:42 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 16:26:03 INFO web_log.py:206 ::1 [27/May/2021:11:26:03 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 16:31:02 INFO web_log.py:206 ::1 [27/May/2021:11:31:02 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 16:31:04 INFO web_log.py:206 ::1 [27/May/2021:11:31:04 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 16:36:59 INFO web_log.py:206 ::1 [27/May/2021:11:36:59 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 16:41:52 INFO web_log.py:206 ::1 [27/May/2021:11:41:52 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 16:47:55 INFO web_log.py:206 ::1 [27/May/2021:11:47:55 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 16:52:35 INFO web_log.py:206 ::1 [27/May/2021:11:52:35 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.21"
2021-05-27 16:53:42 WARNING web_server.py:170 Server has got signal SIGTERM, exiting...
2021-05-27 16:53:42 INFO web_server.py:167 Server has got signal SIGHUP, reloading...
2021-05-27 16:53:42 INFO iou_vm.py:698 Stopping IOU process for IOU VM "S1" PID=32135
2021-05-27 16:53:42 INFO iou_vm.py:698 Stopping IOU process for IOU VM "R2" PID=32127
2021-05-27 16:53:42 INFO iou_vm.py:698 Stopping IOU process for IOU VM "R1" PID=32133
2021-05-27 16:53:42 INFO web_server.py:113 Closing 3 websocket connections...
2021-05-27 16:53:42 INFO __init__.py:154 Controller is reloading
2021-05-27 16:53:43 INFO notification_handler.py:59 Client has disconnected from compute WebSocket
2021-05-27 16:53:43 INFO web_log.py:206 127.0.0.1 [27/May/2021:07:47:20 +0000] "GET /v2/compute/notifications/ws HTTP/1.1" 200 451 "-" "Python/3.9 aiohttp/3.7.4.post0"
2021-05-27 16:53:43 ERROR compute.py:452 Error received on compute 'local' WebSocket 'http://localhost:3080/v2/compute/notifications/ws': Received fragmented control frame
2021-05-27 16:53:43 INFO compute.py:460 Connection closed to compute 'local' WebSocket 'http://localhost:3080/v2/compute/notifications/ws'
2021-05-27 16:53:43 INFO notification_handler.py:82 Client has disconnected from controller WebSocket
2021-05-27 16:53:43 INFO project_handler.py:280 Client has disconnected from notification stream for project ID '2a56fee1-bb43-4cda-a5f5-1ab3c90677e4' (WebSocket method)
2021-05-27 16:53:43 INFO __init__.py:138 Controller is stopping
2021-05-27 16:53:43 INFO base_node.py:331 Builtin: 'NAT1' [9c32e5f4-9a89-4939-82c0-22ddd64553a7]: is closing
2021-05-27 16:53:43 INFO cloud.py:248 Cloud "NAT1" [9c32e5f4-9a89-4939-82c0-22ddd64553a7] has been closed
2021-05-27 16:53:43 INFO base_node.py:331 Docker: 'debian-1' [46701752-b447-49c3-9e1f-6828f9b97d97]: is closing
2021-05-27 16:53:44 INFO docker_vm.py:533 Docker container 'debian-1' fix ownership, state = exited
2021-05-27 16:53:44 INFO docker_vm.py:872 Docker container 'debian-1' [debian:latest] removed
2021-05-27 16:53:44 ERROR base_events.py:1738 Task exception was never retrieved
future: <Task finished name='Task-311' coro=<DockerVM._read_console_output() done, defined at /home/saad/.local/lib/python3.9/site-packages/gns3server/compute/docker/docker_vm.py:710> exception=Docker has returned an error: [Errno 32] Broken pipe>
Traceback (most recent call last):
  File "/home/saad/.local/lib/python3.9/site-packages/gns3server/compute/docker/__init__.py", line 147, in http_query
    response = await self._session.request(method,
  File "/usr/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/usr/lib/python3.9/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/saad/.local/lib/python3.9/site-packages/gns3server/compute/docker/docker_vm.py", line 730, in _read_console_output
    await self.stop()
  File "/home/saad/.local/lib/python3.9/site-packages/gns3server/compute/docker/docker_vm.py", line 786, in stop
    await self._fix_permissions()
  File "/home/saad/.local/lib/python3.9/site-packages/gns3server/compute/docker/docker_vm.py", line 536, in _fix_permissions
    await self.manager.query("POST", "containers/{}/start".format(self._cid))
  File "/home/saad/.local/lib/python3.9/site-packages/gns3server/compute/docker/__init__.py", line 110, in query
    response = await self.http_query(method, path, data=data, params=params)
  File "/home/saad/.local/lib/python3.9/site-packages/gns3server/compute/docker/__init__.py", line 154, in http_query
    raise DockerError("Docker has returned an error: {}".format(str(e)))
gns3server.compute.docker.docker_error.DockerError: Docker has returned an error: [Errno 32] Broken pipe
2021-05-27 16:53:44 INFO base_node.py:331 IOU: 'R1' [f9b76d55-6850-4935-8f45-21e906e87c04]: is closing
2021-05-27 16:53:44 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/lab_for_programming/project-files/iou/f9b76d55-6850-4935-8f45-21e906e87c04/startup-config.cfg
2021-05-27 16:53:44 INFO iou_vm.py:1278 saving private-config to /home/saad/GNS3/projects/lab_for_programming/project-files/iou/f9b76d55-6850-4935-8f45-21e906e87c04/private-config.cfg
2021-05-27 16:53:44 INFO base_node.py:331 IOU: 'R2' [49fc733e-16b0-4831-a5bb-47e90526e662]: is closing
2021-05-27 16:53:44 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/lab_for_programming/project-files/iou/49fc733e-16b0-4831-a5bb-47e90526e662/startup-config.cfg
2021-05-27 16:53:44 INFO iou_vm.py:1278 saving private-config to /home/saad/GNS3/projects/lab_for_programming/project-files/iou/49fc733e-16b0-4831-a5bb-47e90526e662/private-config.cfg
2021-05-27 16:53:44 INFO base_node.py:331 IOU: 'S1' [95ad63d1-5f53-4794-8366-2a7900692b25]: is closing
2021-05-27 16:53:44 INFO iou_vm.py:1268 saving startup-config to /home/saad/GNS3/projects/lab_for_programming/project-files/iou/95ad63d1-5f53-4794-8366-2a7900692b25/startup-config.cfg
2021-05-27 16:53:44 INFO run.py:272 Remove PID file /home/saad/.config/GNS3/2.2/gns3_server.pid
